spring:
  application:
    name: feign-client-demo
server:
  port: 8080
  servlet:
    context-path: /feign-client
app:
  service:
    user:
      name: "app"
      url: "http://localhost:8888/app"

logging:
  level:
    org.springframework.web: DEBUG
    feign: DEBUG
    com.example.feign_client_demo: DEBUG
